blog/urls.py
from django.urls import path
from . import views
from .views import edit_comment, delete_comment, AllSaveView, PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, SaveView, UserPostListView, LikeView,LikeCommentView, posts_of_following_profiles,  AllLikeView

urlpatterns = [
    path('', views.first, name='firsthome'),
    path('home/', PostListView.as_view(), name='blog-home'),
    path('feed/', posts_of_following_profiles, name='posts-follow-view'),
    path('post/user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView, name='post-detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/like/', LikeView, name='post-like'),
    path('liked-posts/', AllLikeView, name='all-like'),
    path('post/save/', SaveView, name='post-save'),
    path('saved-posts/', AllSaveView, name='all-save'),
    path('post/comment/like/', LikeCommentView, name='comment-like'),
    path('about/', views.about, name='blog-about'),
    path('search/', views.search, name='search'),
    path('edit-comment/<int:comment_id>/', edit_comment, name='edit-comment'),
    path('delete-comment/<int:comment_id>/', delete_comment, name='delete-comment'),
]

friend/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from friend.views import cancel_friend_request, decline_friend_request, friend_requests, friends_list_view, remove_friend, send_friend_request, accept_friend_request

app_name = "friend"

urlpatterns = [
    path('list/<user_id>', friends_list_view, name='list'),
    path('friend_request/', send_friend_request, name="friend-request"),
    path('friend_requests/<user_id>/', friend_requests, name='friend-requests'),
    path('friend_request_accept/<friend_request_id>/', accept_friend_request, name='friend-request-accept'),
    path('friend_remove/', remove_friend, name='remove-friend'),
    path('friend_request_decline/<friend_request_id>/', decline_friend_request, name='friend-request-decline'),
    path('friend_request_cancel/', cancel_friend_request, name='friend-request-cancel'),
]

myproject/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),

    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    
    path('accounts/', include('allauth.urls')),
    
    path('', include('blog.urls')),
    path('user/', include('users.urls')),
    path('notifications/', include('notification.urls')),
    path('chats/', include('chat.urls')),
    # path('vc/', include('videocall.urls')),
    path('friend/', include('friend.urls', namespace='friend')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('all/', views.ProfileListView.as_view(), name='profile-list-view'),
    path('follow/', views.follow_unfollow_profile, name='follow-unfollow-view'),
    path('<int:pk>/', views.ProfileDetailView.as_view(), name='profile-detail-view'),
    path('public-profile/<str:username>/', views.public_profile, name='public-profile'),
    
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

""" Model for User Profile """

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_online = models.BooleanField(default=False)
    following = models.ManyToManyField(User, related_name="following", blank=True)
    friends = models.ManyToManyField(User, related_name='my_friends', blank=True)
    bio = models.CharField(default="",blank=True,null=True,max_length=350)
    date_of_birth = models.CharField(blank=True,max_length=150)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics',blank=True, null=True)


    def profile_posts(self):
        return self.user.post_set.all()

    def get_friends(self):
        return self.friends.all()

    def get_friends_no(self):
        return self.friends.all().count()

    def __str__(self):
        return f'{self.user.username} Profile'



STATUS_CHOICES = (
    ('send','send'),
    ('accepted','accepted')
)

class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='friend_sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='friend_receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from PIL import Image

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name','last_name','username','email','password1','password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name','last_name','username','email']


class ProfileUpdateForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)

    image = forms.ImageField(label=('Image'), error_messages = {'invalid':("Image files only")}, widget=forms.FileInput, required=False)
    class Meta:
        model = Profile
        fields = ['bio','date_of_birth','image',]


    """Saving Cropped Image"""
    def save(self,*args,**kwargs):
        img = super(ProfileUpdateForm, self).save(*args, **kwargs)

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        if x and y and w and h:
            image = Image.open(img.image)
            cropped_image = image.crop((x, y, w+x, h+y))
            resized_image = cropped_image.resize((300, 300), Image.ANTIALIAS)
            resized_image.save(img.image.path)

        return img

users/views.py
from friend.models import FriendList, FriendRequest
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from .models import Profile
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.dispatch import receiver 
from django.contrib.auth.signals import user_logged_in, user_logged_out
from notification.models import Notification
import requests
from django.conf import settings
from friend.utils import get_friend_request_or_false
from friend.friend_request_status import FriendRequestStatus


@receiver(user_logged_in)
def got_online(sender, user, request, **kwargs):    
    user.profile.is_online = True
    user.profile.save()

@receiver(user_logged_out)
def got_offline(sender, user, request, **kwargs):   
    user.profile.is_online = False
    user.profile.save()



""" Following and Unfollowing users """
@login_required
def follow_unfollow_profile(request):
    if request.method == 'POST':
        my_profile = Profile.objects.get(user = request.user)
        pk = request.POST.get('profile_pk')
        obj = Profile.objects.get(pk=pk)

        if obj.user in my_profile.following.all():
            my_profile.following.remove(obj.user)
            notify = Notification.objects.filter(sender=request.user, notification_type=2)
            notify.delete()
        else:
            my_profile.following.add(obj.user)
            notify = Notification(sender=request.user, user=obj.user, notification_type=2)
            notify.save()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profile-list-view')


""" User account creation """
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            # # reCAPTCHA V2
            # recaptcha_response = request.POST.get('g-recaptcha-response')
            # data = {
            #     'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            #     'response': recaptcha_response
            # }
            # r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
            # result = r.json()

            # if result['success']:
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Your account has been created! You can login now")
            #     return redirect('login')
            # else:
            #     messages.error(request, 'Invalid reCAPTCHA. Please try again.')            
            
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form':form})


""" User profile """
@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Your account has been updated!")
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    
    context = {
        'u_form':u_form,
        'p_form':p_form
    }

    return render(request, 'users/profile.html', context)


""" Creating a public profile view """
def public_profile(request, username):
    user = User.objects.get(username=username)
    return render(request, 'users/public_profile.html', {"cuser":user})


""" All user profiles """
class ProfileListView(LoginRequiredMixin,ListView):
    model = Profile
    template_name = "users/all_profiles.html"
    context_object_name = "profiles"

    def get_queryset(self):
        return Profile.objects.all().exclude(user=self.request.user)

""" User profile details view """
class ProfileDetailView(LoginRequiredMixin,DetailView):
    model = Profile
    template_name = "users/user_profile_details.html"
    context_object_name = "profiles"

    def get_queryset(self):
        return Profile.objects.all().exclude(user=self.request.user)

    def get_object(self,**kwargs):
        pk = self.kwargs.get("pk")
        view_profile = Profile.objects.get(pk=pk)
        return view_profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        view_profile = self.get_object()
        my_profile = Profile.objects.get(user=self.request.user)
        if view_profile.user in my_profile.following.all():
            follow = True
        else:
            follow = False
        context["follow"] = follow

        # FRIENDS START

        account = view_profile.user
        try:
            friend_list = FriendList.objects.get(user=account)
        except FriendList.DoesNotExist:
            friend_list = FriendList(user=account)
            friend_list.save()
        friends = friend_list.friends.all()
        context['friends']=friends

        is_self = True
        is_friend = False
        request_sent = FriendRequestStatus.NO_REQUEST_SENT.value
        friend_requests = None
        user=self.request.user
        if user.is_authenticated and user!=account:
            is_self = False
            if friends.filter(pk=user.id):
                is_friend = True
            else:
                is_friend = False
                # CASE 1: request from them to you
                if get_friend_request_or_false(sender=account, receiver=user) != False:
                    request_sent = FriendRequestStatus.THEM_SENT_TO_YOU.value
                    context['pending_friend_request_id'] = get_friend_request_or_false(sender=account, receiver=user).pk
                # CASE 2: request you sent to them
                elif get_friend_request_or_false(sender=user, receiver=account) != False:
                    request_sent = FriendRequestStatus.YOU_SENT_TO_THEM.value
                # CASE 3: no request has been sent
                else:
                    request_sent = FriendRequestStatus.NO_REQUEST_SENT.value

        elif not user.is_authenticated:
            is_self = False
        else:
            try:
                friend_requests = FriendRequest.objects.filter(receiver=user, is_active=True)
            except:
                pass
        context['request_sent'] = request_sent
        context['is_friend'] = is_friend
        context['is_self'] = is_self
        context['friend_requests'] = friend_requests
        # FRIENDS END
        
        return context

users/templates/users/logout.html
{% extends "blog/base.html" %}

{% block title %}Logout{% endblock %}

{% block content %}

<div class="container">
    <h2>You have been logged out</h2>    
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'account_login' %}">Login Again</a>
        </small>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "blog/base.html" %}

{% block title %}Password Reset{% endblock %}

{% block content %}

<div class="m-auto col-md-8">
    <div class="alert alert-info">
        Your password has been set.
    </div>
    <a href="{% url 'account_login' %}">Sign In Here</a>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Profile{% endblock %}

{% block content %}

<div class="col-md-8 m-auto">

<div class="content-section">
    
      <div class="account-img-container">
          <div class="img-cont">
            <img class="rounded-circle account-img" src="{{user.profile.image.url}}" alt="image">
            <a class="notify-badge" onclick="picupload()">
                <i class="fas fa-camera"></i>
            </a>
          </div>
      </div>
      <div class="card-body">
          <hr>
          <h4 class="card-title text-center">{{user.first_name}} {{user.last_name}} [{{user.username}}]</h4>
          
    
          <hr>
          <div class="m-t-10 p-20 text-center">
              <div class="row">
                  <div class="col">
                      <span class="h6">Posts</span>
                      <p><a class="mr-2" href="{% url 'user-posts' user %}">{{user.profile.profile_posts.count}}</a></p>
                  </div>
                  <div class="col">
                    <span class="h6">Friends</span>
                    <p title="Friends">
                        <a href="{% url 'friend:list' user.id %}">{{user.friends.all|length}}</a>
                    </p>
                  </div>
                  <div class="col">
                      <span class="h6">Followers</span>
                      <p>{{user.following.count}}</p>
                  </div>
                  <div class="col">
                      <span class="h6">Following</span>
                      <p>{{user.profile.following.count}}</p>
                  </div>
              </div>
          </div>
      </div>
    
    <form id="formUpload" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Info</legend>
            {{u_form|crispy}}
            {{p_form|crispy}}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Update</button>
        </div>
    </form>
</div>





<!-- Modal -->
<div class="modal fade" id="modalCrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Crop the photo</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button> 
        </div>
        <div class="modal-body" style="max-width: 100%; overflow:auto">
            <img style="max-height:100%; max-width: 100%" src="" id="image">
        </div>
        <div class="modal-footer">
            <div class="float-left">
                <button type="button" class="btn btn-primary js-zoom-in">
                    <i class="fas fa-search-plus"></i>
                </button>
                <button type="button" class="btn btn-primary js-zoom-out">
                    <i class="fas fa-search-minus"></i>
                </button>
            </div>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
        </div>
      </div>
    </div>
</div>

</div>

{% endblock %}

{% block script %}
    <script>
        function picupload(){
            const imgf = document.getElementById('id_image')
            imgf.click()
        }
    </script>
{% endblock %}

users/templates/users/user_profile_details.html
{% extends "blog/base.html" %}

{% block title %}User profile{% endblock %}

{% block content %}

<div class="col-md-8">

<div class="content-section" style="width: 100%">
    <div class="account-img-container">
        <div class="img-cont">
            <img class="rounded-circle account-img" src="{{object.user.profile.image.url}}" alt="image">
            {% if object.user.profile.is_online %}
                <div class="online-circle"></div>
            {% else %}
                <div class="offline-circle"></div>
            {% endif %}
        </div>
    </div>
    <div class="card-body">
        <hr>
        <h4 class="card-title text-center">{{object.user.first_name}} {{object.user.last_name}} [{{object.user.username}}]</h4>
        <p class="card-text text-center text-muted">{{object.user.email}}</p>
        <p class="card-text text-center text-muted">{{object.user.profile.bio}}</p>

		<ul class="social-links list-inline text-center m-4">
			<li class="list-inline-item m-1"><a title="" data-placement="top" data-toggle="tooltip" class="tooltips btn-primary" href="" data-original-title="Facebook"><i class="fab fa-facebook-f"></i></a></li>
			<li class="list-inline-item m-1"><a title="" data-placement="top" data-toggle="tooltip" class="tooltips btn-info" href="" data-original-title="Twitter"><i class="fab fa-twitter"></i></a></li>
			<li class="list-inline-item m-1"><a title="" data-placement="top" data-toggle="tooltip" class="tooltips btn-danger" href="" data-original-title="Skype"><i class="fab fa-instagram"></i></a></li>
			<li class="list-inline-item m-1"><a title="" data-placement="top" data-toggle="tooltip" class="tooltips btn-primary" href="" data-original-title="Linkedin"><i class="fab fa-linkedin"></i></a></li>
		</ul>

        <div class="text-center">
            {% if object.user != user %}
                {% if follow %}
                    <form action="{% url 'follow-unfollow-view' %}" method='POST'>
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{object.pk}}>
                        <button type="submit" class="btn btn-danger mb-2 w-50">Unfollow</button>
                    </form>
                {% else %}
                    <form action="{% url 'follow-unfollow-view' %}" method='POST'>
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{object.pk}}>
                        <button type="submit" class="btn btn-primary mb-2 w-50">Follow</button>
                    </form>
                {% endif %}
            {% endif %}

			<!-- THEM to YOU -->
			{% if request_sent == 0 %}
				<div class="card m-2 p-4">
					<div class="flex text-center align-items-center">
						<p class="align-items-center mr-2 h5 text-muted">Accept Friend Request</p>
						<span id="id_cancel_{{object.user.id}}" class="decline-friend-request material-icons p-1 m-1" onclick='triggerDeclineFriendRequest("{{pending_friend_request_id}}")'><i class="fas fa-times-circle"></i></span>
						<span id="id_confirm_{{object.user.id}}" class="confirm-friend-request material-icons p-1 m-1" onclick='triggerAcceptFriendRequest("{{pending_friend_request_id}}")'><i class="fas fa-check-circle"></i></span>
					</div>
				</div>
			{% endif %}
			
			<!-- Cancel Friend Request / Send Friend Request / Remove Friend -->
			{% if is_friend == False and is_self == False %}
				<!-- You sent them a request -->
				{% if request_sent == 1 %}
					<div class="d-flex flex-column align-items-center pt-4">
						<button class="btn btn-danger w-50" id="id_cancel_friend_request_btn">
							Cancel Friend Request
						</button>
					</div>
				{% endif %}
				<!-- No requests have been sent -->
				{% if request_sent == -1 %}
					<div class="d-flex flex-column align-items-center pt-4">
						<button class="btn btn-primary w-50" id="id_send_friend_request_btn">
							Send Friend Request
						</button>
					</div>
				{% endif %}
			{% endif %}
				
			{% if is_friend %}
				<div class="dropdown pt-4 m-auto">
					<button class="btn btn-success dropdown-toggle friends-btn w-50" type="button" id="id_friends_toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Friends
					</button>
					<div class="dropdown-menu" aria-labelledby="id_friends_toggle">
						<a class="dropdown-item" href="#" onclick="removeFriend('{{object.user.id}}', onFriendRemoved)">Unfriend</a>
					</div>
				</div>
			{% endif %}

			{% if friend_requests %}
				<div class="card m-2 px-4 pb-4">
					<!-- Friend requests -->
					<div class="d-flex flex-column pt-4">
						<a href="{% url 'friend:friend-requests' user_id=object.user.id %}">
							<div class="d-flex flex-row align-items-center justify-content-center icon-container">
								<span class="friend-text">Friend Requests ({{friend_requests|length}})</span>
							</div>
						</a>
					</div>
				</div>
			{% endif %}

        </div>
        <hr>


        <div class="m-t-10 p-15 text-center">
            <div class="row">
                <div class="col">
                    <span class="h6">Posts</span>
                    <p><a class="mr-2" href="{% url 'user-posts' object.user %}">{{object.profile_posts.count}}</a></p>
                </div>
                <div class="col">
                    <span class="h6">Friends</span>
                    <p title="Friends">
                        <a href="{% url 'friend:list' object.user.id %}">{{friends|length}}</a>
                    </p>
                </div>
                <div class="col">
                    <span class="h6">Followers</span>
                    <p style="cursor:pointer; color: blue;" data-toggle="modal" data-target="#exampleModal" data-contents="{{object.user.following.all}}" data-title="Followers" title="Followers">{{object.user.following.count}}</p>
                </div>
                <div class="col">
                    <span class="h6">Following</span>
					<p style="cursor:pointer; color: blue;" data-toggle="modal" data-target="#exampleModal" data-contents="{{object.user.profile.following.all}}" data-title="Following" title="Following">{{object.user.profile.following.count}}</p>
                </div>
            </div>
        </div>
    </div>
</div>

<br>




<style type="text/css">

.social-links li a {
    border-radius: 50%;
    color: rgba(255, 255, 255);
    display: inline-block;
    height: 40px;
    line-height: 35px;
    border: 2px solid transparent;
    text-align: center;
    width: 40px;
	font-size: 14px;
}



	.profile-image{
		max-height: 100px;
		max-width: 100px;
	}
	.profile-image{
		border-radius: 12px;
	}
	.card{
		border-radius: 12px;
	}
	
	.profile-link{
		color: #000;
	}
	.material-icons{
		font-size: 30px;
	}
	.material-icons:hover{
		cursor: pointer;
	}
	.confirm-friend-request{
		color: green;
	}
	.confirm-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request{
		color: red;
	}
</style>

<div>

	{% if is_friend %}
		<a class="align-items-center btn btn-primary d-flex flex-column" href="{% url 'room-choice' object.user.id %}">
			<i class="fas fa-comments"></i>&nbsp;&nbsp;Message
		</a>
	{% endif %}

</div>

<br>

</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
	  <div class="modal-content">
		<div class="modal-header">
		  <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
		  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		  </button>
		</div>
		<div class="modal-body">
		  ...
		</div>
		<div class="modal-footer">
		  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		</div>
	  </div>
	</div>
</div>


<!-- SIDEBAR -->
<div class="col-md-4">
    <div class="content-section">
		<h4>Posts by {{object.user}} ({{object.profile_posts.count}}) : </h4>

		{% if object.profile_posts.count == 0 %}
			<br>
			<span class="text-muted">{{object.user.username}} has not posted anything yet</span>
			<br>
		{% endif %}

		{% for post in object.profile_posts %}
			<hr>
			<div>
				<a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a>
			</div>
		{% endfor %}
		<br>
	</div>
</div>  


<script type="text/javascript">

	function onFriendRequestSent(){
		location.reload();
	}

	function onFriendRequestCancelled(){
		location.reload();
	}

	function onFriendRemoved(){
		location.reload();
	}

	function onFriendRequestAccepted(){
		location.reload();
	}

	function onFriendRequestDeclined(){
		location.reload();
	}


	var sendFriendRequestBtn = document.getElementById("id_send_friend_request_btn")
	if (sendFriendRequestBtn != null){
		sendFriendRequestBtn.addEventListener("click", function(){
			sendFriendRequest("{{object.user.id}}", onFriendRequestSent)
		})
	}

	var cancelFriendRequestBtn = document.getElementById("id_cancel_friend_request_btn")
	if(cancelFriendRequestBtn != null){
		cancelFriendRequestBtn.addEventListener("click", function(){
			cancelFriendRequest("{{object.user.id}}", onFriendRequestCancelled)
		})
	}

	var removeFriendBtn = document.getElementById("id_unfriend_btn")
	if (removeFriendBtn != null){
		removeFriendBtn.addEventListener("click", function(){
			removeFriend("{{object.user.id}}", onFriendRemoved)
		})
	}

	function triggerAcceptFriendRequest(friend_request_id){
		acceptFriendRequest(friend_request_id, onFriendRequestAccepted)
	}

	function triggerDeclineFriendRequest(friend_request_id){
		declineFriendRequest(friend_request_id, onFriendRequestDeclined)
	}
	
</script>

{% include 'friend/snippets/send_friend_request.html' %}
{% include 'friend/snippets/accept_friend_request.html' %}
{% include 'friend/snippets/decline_friend_request.html' %}
{% include 'friend/snippets/cancel_friend_request.html' %}
{% include 'friend/snippets/remove_friend.html' %}


{% endblock %}

{% block script %}

<script>
	$('#exampleModal').on('show.bs.modal', function (event) {
		var button = $(event.relatedTarget) 
		var mcontents = button.data('contents') 
		var mtitle = button.data('title') 
		
		var modal = $(this)
		var mlist = ""
		var mbody = ""

		if (mtitle === "Followers") {
			mtitle = mtitle + ' ({{object.user.following.count}})'
			{% for fs in object.user.following.all %}
				mlist += `<li class="m-1">
							<a href="{% url 'profile-detail-view' pk=fs.pk %}">
								{{fs.user}}
							</a>
						</li>`
			{% endfor %}
			mbody = `<ul>${mlist}</ul>`
		}
		if (mtitle === "Following") {
			mtitle = mtitle + ' ({{object.user.profile.following.count}})'
			{% for fs in object.user.profile.following.all %}
				mlist += `<li class="m-1">
							<a href="{% url 'profile-detail-view' pk=fs.pk %}">
								{{fs.user}}
							</a>
						</li>`
			{% endfor %}
			mbody = `<ul>${mlist}</ul>`
		}
		modal.find('.modal-title').text(mtitle)
		modal.find('.modal-body').html(mbody)
	});
</script>

	
{% endblock %}